{% set name = "obsplus" %}
{% set version = "0.1.0" %}
{% set sha256 = "9d3d2fe7e8ce243103790cd49d3421ff200fc2e12394e99d11b792f02ef40a38" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - pip
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.13.0
    - obspy >=1.2.1
    - pandas >=0.24.0
    - progressbar2
    - scipy
    - setuptools
    - pytables

test:
  imports:
    - obsplus

about:
  home: https://github.com/niosh-mining/obsplus
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE.txt
  summary: 'An Pandas-Centric ObsPy Expansion Pack'
  description: |
    ObsPlus is a utility package for ObsPy.
  doc_url: https://github.com/niosh-mining/obsplus
  dev_url: https://github.com/niosh-mining/obsplus

extra:
  recipe-maintainers:
    - d-chambers
